apiVersion: v1
kind: Service
metadata:
  name: version-update
spec:
  selector:
    app: version-update
    version: v1 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
