apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746669234841:role/eksctl-verison-update-poc-addon-iamserviceacc-Role1-tWsqgkiUek1v
