apiVersion: v1
kind: Service
metadata:
  name: myapp-kickstart
spec:
  selector:
    app: myapp
    version: kickstart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-scoops
spec:
  selector:
    app: myapp
    version: scoops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
