name: Blue-Green Traffic Switch

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: "Which version to route traffic to?"
        required: true
        default: kickstart
        type: choice
        options:
          - kickstart
          - scoops

jobs:
  switch:
    name: Switch Traffic to ${{ github.event.inputs.target_version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name verison-update-poc --region us-east-1

      - name: Patch Service to Switch Traffic
        run: |
          kubectl patch service myapp-service \
            -p "{\"spec\": {\"selector\": {\"app\": \"myapp\", \"version\": \"${{ github.event.inputs.target_version }}\"}}}"

      - name: Confirm Service Routing
        run: |
          kubectl get service myapp-service -o jsonpath='{.spec.selector}'
