name: Blue-Green EKS Deployment with Ingress

on:
  workflow_dispatch:
    inputs:
      deploy_to:
        description: 'Which version to deploy and route traffic to? (kickstart or scoops)'
        required: true
        default: 'scoops'

jobs:
  deploy:
    name: Deploy to EKS with Ingress
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --name verison-update-poc \
          --region ${{ secrets.AWS_REGION }}

    - name: Apply service and deployment
      run: |
        kubectl apply -f k8s/deployment-${{ github.event.inputs.deploy_to }}.yaml
        kubectl apply -f k8s/service.yaml

    - name: Apply Ingress rule
      run: |
        kubectl apply -f k8s/ingress.yaml

    - name: Verify Ingress
      run: |
        echo "Waiting for ALB to be ready..."
        kubectl get ingress myapp-ingress -w --timeout=90s || true
