name: Blue-Green Deployment (EKS)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: version-update-poc
      REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - name: Apply Blue Deployment
        run: kubectl apply -f blue-deployment.yaml

      - name: Apply Green Deployment
        run: kubectl apply -f green-deployment.yaml

      - name: Wait for Green Deployment to be Ready
        run: kubectl rollout status deployment green-deployment

      - name: Health Check on Green Pod
        run: |
          GREEN_POD=$(kubectl get pods -l version=v2 -o jsonpath="{.items[0].metadata.name}")
          kubectl exec "$GREEN_POD" -- curl -s localhost:80

      - name: Switch Traffic to Green
        run: |
          kubectl patch service sample-service \
            -p '{"spec":{"selector":{"app":"sample-app","version":"v2"}}}'
